// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "draw_event.proto" (package "draw", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message draw.Point
 */
export interface Point {
    /**
     * @generated from protobuf field: double x = 1
     */
    x: number;
    /**
     * @generated from protobuf field: double y = 2
     */
    y: number;
}
/**
 * @generated from protobuf message draw.FillStyle
 */
export interface FillStyle {
    /**
     * @generated from protobuf field: string color = 1
     */
    color: string;
    /**
     * @generated from protobuf field: double opacity = 2
     */
    opacity: number;
}
/**
 * @generated from protobuf message draw.DrawEventBase
 */
export interface DrawEventBase {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string strokeColor = 2
     */
    strokeColor: string;
    /**
     * @generated from protobuf field: int32 strokeWidth = 3
     */
    strokeWidth: number;
    /**
     * @generated from protobuf field: int64 timestamp = 4
     */
    timestamp: bigint;
    /**
     * @generated from protobuf field: string type = 5
     */
    type: string;
}
/**
 * @generated from protobuf message draw.LineEvent
 */
export interface LineEvent {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string strokeColor = 2
     */
    strokeColor: string;
    /**
     * @generated from protobuf field: int32 strokeWidth = 3
     */
    strokeWidth: number;
    /**
     * @generated from protobuf field: int64 timestamp = 4
     */
    timestamp: bigint;
    /**
     * @generated from protobuf field: string type = 5
     */
    type: string;
    /**
     * @generated from protobuf field: draw.Point from = 6
     */
    from?: Point;
    /**
     * @generated from protobuf field: draw.Point to = 7
     */
    to?: Point;
}
/**
 * @generated from protobuf message draw.CircleEvent
 */
export interface CircleEvent {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string strokeColor = 2
     */
    strokeColor: string;
    /**
     * @generated from protobuf field: int32 strokeWidth = 3
     */
    strokeWidth: number;
    /**
     * @generated from protobuf field: int64 timestamp = 4
     */
    timestamp: bigint;
    /**
     * @generated from protobuf field: string type = 5
     */
    type: string;
    /**
     * @generated from protobuf field: double radius = 6
     */
    radius: number;
    /**
     * @generated from protobuf field: draw.Point center = 7
     */
    center?: Point;
    /**
     * @generated from protobuf field: optional draw.FillStyle fillStyle = 8
     */
    fillStyle?: FillStyle;
}
/**
 * @generated from protobuf message draw.PolygonEvent
 */
export interface PolygonEvent {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string strokeColor = 2
     */
    strokeColor: string;
    /**
     * @generated from protobuf field: int32 strokeWidth = 3
     */
    strokeWidth: number;
    /**
     * @generated from protobuf field: int64 timestamp = 4
     */
    timestamp: bigint;
    /**
     * @generated from protobuf field: string type = 5
     */
    type: string;
    /**
     * @generated from protobuf field: repeated draw.Point points = 6
     */
    points: Point[];
    /**
     * @generated from protobuf field: optional draw.FillStyle fillStyle = 7
     */
    fillStyle?: FillStyle;
}
/**
 * @generated from protobuf message draw.DrawEvent
 */
export interface DrawEvent {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string strokeColor = 2
     */
    strokeColor: string;
    /**
     * @generated from protobuf field: int32 strokeWidth = 3
     */
    strokeWidth: number;
    /**
     * @generated from protobuf field: int64 timestamp = 4
     */
    timestamp: bigint;
    /**
     * @generated from protobuf field: string type = 5
     */
    type: string;
    /**
     * for PolygonEvent
     *
     * @generated from protobuf field: repeated draw.Point points = 6
     */
    points: Point[];
    /**
     * @generated from protobuf field: optional draw.FillStyle fillStyle = 7
     */
    fillStyle?: FillStyle;
    /**
     * for LineEvent
     *
     * @generated from protobuf field: optional draw.Point from = 8
     */
    from?: Point;
    /**
     * @generated from protobuf field: optional draw.Point to = 9
     */
    to?: Point;
    /**
     * for CircleEvent
     *
     * @generated from protobuf field: optional double radius = 10
     */
    radius?: number;
    /**
     * @generated from protobuf field: optional draw.Point center = 11
     */
    center?: Point;
}
/**
 * @generated from protobuf message draw.DrawEventList
 */
export interface DrawEventList {
    /**
     * @generated from protobuf field: repeated draw.DrawEvent events = 1
     */
    events: DrawEvent[];
    /**
     * @generated from protobuf field: int64 timestamp = 2
     */
    timestamp: bigint;
}
// @generated message type with reflection information, may provide speed optimized methods
class Point$Type extends MessageType<Point> {
    constructor() {
        super("draw.Point", [
            { no: 1, name: "x", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 2, name: "y", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
    create(value?: PartialMessage<Point>): Point {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.x = 0;
        message.y = 0;
        if (value !== undefined)
            reflectionMergePartial<Point>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Point): Point {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* double x */ 1:
                    message.x = reader.double();
                    break;
                case /* double y */ 2:
                    message.y = reader.double();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Point, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* double x = 1; */
        if (message.x !== 0)
            writer.tag(1, WireType.Bit64).double(message.x);
        /* double y = 2; */
        if (message.y !== 0)
            writer.tag(2, WireType.Bit64).double(message.y);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message draw.Point
 */
export const Point = new Point$Type();
// @generated message type with reflection information, may provide speed optimized methods
class FillStyle$Type extends MessageType<FillStyle> {
    constructor() {
        super("draw.FillStyle", [
            { no: 1, name: "color", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "opacity", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
    create(value?: PartialMessage<FillStyle>): FillStyle {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.color = "";
        message.opacity = 0;
        if (value !== undefined)
            reflectionMergePartial<FillStyle>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: FillStyle): FillStyle {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string color */ 1:
                    message.color = reader.string();
                    break;
                case /* double opacity */ 2:
                    message.opacity = reader.double();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: FillStyle, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string color = 1; */
        if (message.color !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.color);
        /* double opacity = 2; */
        if (message.opacity !== 0)
            writer.tag(2, WireType.Bit64).double(message.opacity);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message draw.FillStyle
 */
export const FillStyle = new FillStyle$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DrawEventBase$Type extends MessageType<DrawEventBase> {
    constructor() {
        super("draw.DrawEventBase", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "strokeColor", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "strokeWidth", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "timestamp", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 5, name: "type", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<DrawEventBase>): DrawEventBase {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.strokeColor = "";
        message.strokeWidth = 0;
        message.timestamp = 0n;
        message.type = "";
        if (value !== undefined)
            reflectionMergePartial<DrawEventBase>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DrawEventBase): DrawEventBase {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string strokeColor */ 2:
                    message.strokeColor = reader.string();
                    break;
                case /* int32 strokeWidth */ 3:
                    message.strokeWidth = reader.int32();
                    break;
                case /* int64 timestamp */ 4:
                    message.timestamp = reader.int64().toBigInt();
                    break;
                case /* string type */ 5:
                    message.type = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DrawEventBase, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string strokeColor = 2; */
        if (message.strokeColor !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.strokeColor);
        /* int32 strokeWidth = 3; */
        if (message.strokeWidth !== 0)
            writer.tag(3, WireType.Varint).int32(message.strokeWidth);
        /* int64 timestamp = 4; */
        if (message.timestamp !== 0n)
            writer.tag(4, WireType.Varint).int64(message.timestamp);
        /* string type = 5; */
        if (message.type !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.type);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message draw.DrawEventBase
 */
export const DrawEventBase = new DrawEventBase$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LineEvent$Type extends MessageType<LineEvent> {
    constructor() {
        super("draw.LineEvent", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "strokeColor", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "strokeWidth", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "timestamp", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 5, name: "type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "from", kind: "message", T: () => Point },
            { no: 7, name: "to", kind: "message", T: () => Point }
        ]);
    }
    create(value?: PartialMessage<LineEvent>): LineEvent {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.strokeColor = "";
        message.strokeWidth = 0;
        message.timestamp = 0n;
        message.type = "";
        if (value !== undefined)
            reflectionMergePartial<LineEvent>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LineEvent): LineEvent {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string strokeColor */ 2:
                    message.strokeColor = reader.string();
                    break;
                case /* int32 strokeWidth */ 3:
                    message.strokeWidth = reader.int32();
                    break;
                case /* int64 timestamp */ 4:
                    message.timestamp = reader.int64().toBigInt();
                    break;
                case /* string type */ 5:
                    message.type = reader.string();
                    break;
                case /* draw.Point from */ 6:
                    message.from = Point.internalBinaryRead(reader, reader.uint32(), options, message.from);
                    break;
                case /* draw.Point to */ 7:
                    message.to = Point.internalBinaryRead(reader, reader.uint32(), options, message.to);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LineEvent, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string strokeColor = 2; */
        if (message.strokeColor !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.strokeColor);
        /* int32 strokeWidth = 3; */
        if (message.strokeWidth !== 0)
            writer.tag(3, WireType.Varint).int32(message.strokeWidth);
        /* int64 timestamp = 4; */
        if (message.timestamp !== 0n)
            writer.tag(4, WireType.Varint).int64(message.timestamp);
        /* string type = 5; */
        if (message.type !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.type);
        /* draw.Point from = 6; */
        if (message.from)
            Point.internalBinaryWrite(message.from, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* draw.Point to = 7; */
        if (message.to)
            Point.internalBinaryWrite(message.to, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message draw.LineEvent
 */
export const LineEvent = new LineEvent$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CircleEvent$Type extends MessageType<CircleEvent> {
    constructor() {
        super("draw.CircleEvent", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "strokeColor", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "strokeWidth", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "timestamp", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 5, name: "type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "radius", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 7, name: "center", kind: "message", T: () => Point },
            { no: 8, name: "fillStyle", kind: "message", T: () => FillStyle }
        ]);
    }
    create(value?: PartialMessage<CircleEvent>): CircleEvent {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.strokeColor = "";
        message.strokeWidth = 0;
        message.timestamp = 0n;
        message.type = "";
        message.radius = 0;
        if (value !== undefined)
            reflectionMergePartial<CircleEvent>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CircleEvent): CircleEvent {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string strokeColor */ 2:
                    message.strokeColor = reader.string();
                    break;
                case /* int32 strokeWidth */ 3:
                    message.strokeWidth = reader.int32();
                    break;
                case /* int64 timestamp */ 4:
                    message.timestamp = reader.int64().toBigInt();
                    break;
                case /* string type */ 5:
                    message.type = reader.string();
                    break;
                case /* double radius */ 6:
                    message.radius = reader.double();
                    break;
                case /* draw.Point center */ 7:
                    message.center = Point.internalBinaryRead(reader, reader.uint32(), options, message.center);
                    break;
                case /* optional draw.FillStyle fillStyle */ 8:
                    message.fillStyle = FillStyle.internalBinaryRead(reader, reader.uint32(), options, message.fillStyle);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CircleEvent, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string strokeColor = 2; */
        if (message.strokeColor !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.strokeColor);
        /* int32 strokeWidth = 3; */
        if (message.strokeWidth !== 0)
            writer.tag(3, WireType.Varint).int32(message.strokeWidth);
        /* int64 timestamp = 4; */
        if (message.timestamp !== 0n)
            writer.tag(4, WireType.Varint).int64(message.timestamp);
        /* string type = 5; */
        if (message.type !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.type);
        /* double radius = 6; */
        if (message.radius !== 0)
            writer.tag(6, WireType.Bit64).double(message.radius);
        /* draw.Point center = 7; */
        if (message.center)
            Point.internalBinaryWrite(message.center, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* optional draw.FillStyle fillStyle = 8; */
        if (message.fillStyle)
            FillStyle.internalBinaryWrite(message.fillStyle, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message draw.CircleEvent
 */
export const CircleEvent = new CircleEvent$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PolygonEvent$Type extends MessageType<PolygonEvent> {
    constructor() {
        super("draw.PolygonEvent", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "strokeColor", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "strokeWidth", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "timestamp", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 5, name: "type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "points", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Point },
            { no: 7, name: "fillStyle", kind: "message", T: () => FillStyle }
        ]);
    }
    create(value?: PartialMessage<PolygonEvent>): PolygonEvent {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.strokeColor = "";
        message.strokeWidth = 0;
        message.timestamp = 0n;
        message.type = "";
        message.points = [];
        if (value !== undefined)
            reflectionMergePartial<PolygonEvent>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PolygonEvent): PolygonEvent {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string strokeColor */ 2:
                    message.strokeColor = reader.string();
                    break;
                case /* int32 strokeWidth */ 3:
                    message.strokeWidth = reader.int32();
                    break;
                case /* int64 timestamp */ 4:
                    message.timestamp = reader.int64().toBigInt();
                    break;
                case /* string type */ 5:
                    message.type = reader.string();
                    break;
                case /* repeated draw.Point points */ 6:
                    message.points.push(Point.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* optional draw.FillStyle fillStyle */ 7:
                    message.fillStyle = FillStyle.internalBinaryRead(reader, reader.uint32(), options, message.fillStyle);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PolygonEvent, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string strokeColor = 2; */
        if (message.strokeColor !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.strokeColor);
        /* int32 strokeWidth = 3; */
        if (message.strokeWidth !== 0)
            writer.tag(3, WireType.Varint).int32(message.strokeWidth);
        /* int64 timestamp = 4; */
        if (message.timestamp !== 0n)
            writer.tag(4, WireType.Varint).int64(message.timestamp);
        /* string type = 5; */
        if (message.type !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.type);
        /* repeated draw.Point points = 6; */
        for (let i = 0; i < message.points.length; i++)
            Point.internalBinaryWrite(message.points[i], writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* optional draw.FillStyle fillStyle = 7; */
        if (message.fillStyle)
            FillStyle.internalBinaryWrite(message.fillStyle, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message draw.PolygonEvent
 */
export const PolygonEvent = new PolygonEvent$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DrawEvent$Type extends MessageType<DrawEvent> {
    constructor() {
        super("draw.DrawEvent", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "strokeColor", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "strokeWidth", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "timestamp", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 5, name: "type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "points", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Point },
            { no: 7, name: "fillStyle", kind: "message", T: () => FillStyle },
            { no: 8, name: "from", kind: "message", T: () => Point },
            { no: 9, name: "to", kind: "message", T: () => Point },
            { no: 10, name: "radius", kind: "scalar", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 11, name: "center", kind: "message", T: () => Point }
        ]);
    }
    create(value?: PartialMessage<DrawEvent>): DrawEvent {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.strokeColor = "";
        message.strokeWidth = 0;
        message.timestamp = 0n;
        message.type = "";
        message.points = [];
        if (value !== undefined)
            reflectionMergePartial<DrawEvent>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DrawEvent): DrawEvent {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string strokeColor */ 2:
                    message.strokeColor = reader.string();
                    break;
                case /* int32 strokeWidth */ 3:
                    message.strokeWidth = reader.int32();
                    break;
                case /* int64 timestamp */ 4:
                    message.timestamp = reader.int64().toBigInt();
                    break;
                case /* string type */ 5:
                    message.type = reader.string();
                    break;
                case /* repeated draw.Point points */ 6:
                    message.points.push(Point.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* optional draw.FillStyle fillStyle */ 7:
                    message.fillStyle = FillStyle.internalBinaryRead(reader, reader.uint32(), options, message.fillStyle);
                    break;
                case /* optional draw.Point from */ 8:
                    message.from = Point.internalBinaryRead(reader, reader.uint32(), options, message.from);
                    break;
                case /* optional draw.Point to */ 9:
                    message.to = Point.internalBinaryRead(reader, reader.uint32(), options, message.to);
                    break;
                case /* optional double radius */ 10:
                    message.radius = reader.double();
                    break;
                case /* optional draw.Point center */ 11:
                    message.center = Point.internalBinaryRead(reader, reader.uint32(), options, message.center);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DrawEvent, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string strokeColor = 2; */
        if (message.strokeColor !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.strokeColor);
        /* int32 strokeWidth = 3; */
        if (message.strokeWidth !== 0)
            writer.tag(3, WireType.Varint).int32(message.strokeWidth);
        /* int64 timestamp = 4; */
        if (message.timestamp !== 0n)
            writer.tag(4, WireType.Varint).int64(message.timestamp);
        /* string type = 5; */
        if (message.type !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.type);
        /* repeated draw.Point points = 6; */
        for (let i = 0; i < message.points.length; i++)
            Point.internalBinaryWrite(message.points[i], writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* optional draw.FillStyle fillStyle = 7; */
        if (message.fillStyle)
            FillStyle.internalBinaryWrite(message.fillStyle, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* optional draw.Point from = 8; */
        if (message.from)
            Point.internalBinaryWrite(message.from, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        /* optional draw.Point to = 9; */
        if (message.to)
            Point.internalBinaryWrite(message.to, writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        /* optional double radius = 10; */
        if (message.radius !== undefined)
            writer.tag(10, WireType.Bit64).double(message.radius);
        /* optional draw.Point center = 11; */
        if (message.center)
            Point.internalBinaryWrite(message.center, writer.tag(11, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message draw.DrawEvent
 */
export const DrawEvent = new DrawEvent$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DrawEventList$Type extends MessageType<DrawEventList> {
    constructor() {
        super("draw.DrawEventList", [
            { no: 1, name: "events", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => DrawEvent },
            { no: 2, name: "timestamp", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<DrawEventList>): DrawEventList {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.events = [];
        message.timestamp = 0n;
        if (value !== undefined)
            reflectionMergePartial<DrawEventList>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DrawEventList): DrawEventList {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated draw.DrawEvent events */ 1:
                    message.events.push(DrawEvent.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* int64 timestamp */ 2:
                    message.timestamp = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DrawEventList, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated draw.DrawEvent events = 1; */
        for (let i = 0; i < message.events.length; i++)
            DrawEvent.internalBinaryWrite(message.events[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* int64 timestamp = 2; */
        if (message.timestamp !== 0n)
            writer.tag(2, WireType.Varint).int64(message.timestamp);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message draw.DrawEventList
 */
export const DrawEventList = new DrawEventList$Type();
